LANGUAGES = {
    "English": "en",
    "اردو (Urdu)": "ur",
    "العربية (Arabic)": "ar",
    "हिन्दी (Hindi)": "hi",
    "Français (French)": "fr",
    "Español (Spanish)": "es",
}

_UI_STRINGS = {
    "English": {
        "new_chat": "New Chat",
        "navigation": "Navigation",
        "chat": "💬 Chat",
        "dashboard": "📊 Dashboard",
        "medicine_tracker": "💊 Medicine Tracker",
        "language": "Language",
        "upload_docs": "Medical Documents",
        "upload_pdf": "Upload PDF Report",
        "processing": "Processing PDF...",
        "voice_mode": "Voice Mode",
        "disclaimer": "For informational use only. Not a substitute for professional medical advice.",
        "powered_by": "Powered by Groq × LLaMA 3.3",
        "welcome_title": "How can I help you today?",
        "welcome_sub": "Describe symptoms, upload medical reports or images, and get structured safety-focused guidance.",
        "suggestions": [
            "🤒 I have fever and headache since 2 days",
            "💊 I want general OTC medicine guidance",
            "🖼️ Analyze my X-ray report",
            "🌙 When should I take my medicine?",
        ],
        "attach": "Attach Image",
        "upload_image": "Upload medical image (X-ray, skin, etc.)",
        "speak_now": "Speak your symptoms...",
        "transcribing": "Transcribing...",
        "input_placeholder": "Describe your symptoms or ask a medical question...",
        "thinking": "Preparing clinical guidance...",
        "analyze_image_prompt": "Please analyze this medical image and provide cautious observations.",
        "history_title": "📋 Diagnosis History",
        "no_history": "No diagnosis history yet. Start a conversation!",
        "clear_history": "🗑️ Clear History",
        "med_tracker_title": "💊 Medicine Tracker",
        "add_medicine": "Add Medicine",
        "med_name": "Medicine Name",
        "dosage": "Dosage",
        "timing": "Timing",
        "duration": "Duration",
        "notes": "Notes (optional)",
        "save_med": "Save Medicine",
        "your_medicines": "Your Medicines",
        "no_meds": "No medicines added yet.",
        "morning": "🌅 Morning",
        "night": "🌙 Night",
        "after_meals": "🍽️ After Meals",
        "before_meals": "Before Meals",
        "twice_daily": "Twice Daily",
        "dashboard_title": "📊 Patient Dashboard",
        "total_chats": "Total Consultations",
        "active_meds": "Active Medicines",
        "recent_diagnosis": "Recent Diagnoses",
        "medicine_history": "Medicine History",
        "query": "Question",
        "response": "Response",
        "date": "Date",
        "status": "Status",
        "active": "Active",
        "stopped": "Stopped",
        "stop": "Stop",
        "delete": "Delete",
    },
    "اردو (Urdu)": {
        "new_chat": "نئی گفتگو",
        "navigation": "نیویگیشن",
        "chat": "💬 گفتگو",
        "dashboard": "📊 ڈیش بورڈ",
        "medicine_tracker": "💊 دوائی ٹریکر",
        "language": "زبان",
        "upload_docs": "طبی دستاویزات",
        "upload_pdf": "PDF رپورٹ اپلوڈ کریں",
        "processing": "PDF پروسیس ہو رہی ہے...",
        "voice_mode": "آواز موڈ",
        "disclaimer": "صرف معلوماتی مقاصد کے لیے۔ طبی مشورے کا متبادل نہیں۔",
        "powered_by": "Groq × LLaMA 3.3 سے چلتا ہے",
        "welcome_title": "آج میں آپ کی کیا مدد کر سکتا ہوں؟",
        "welcome_sub": "علامات بتائیں، دوائی کی سفارش لیں، یا طبی تصاویر اور رپورٹس اپلوڈ کریں۔",
        "suggestions": [
            "🤒 مجھے دو دن سے بخار اور سر درد ہے",
            "💊 ہائی بلڈ پریشر کی دوائی کیا ہے؟",
            "🖼️ میری ایکسرے رپورٹ دیکھیں",
            "🌙 دوائی کب لینی چاہیے؟",
        ],
        "attach": "تصویر منسلک کریں",
        "upload_image": "طبی تصویر اپلوڈ کریں (ایکسرے، جلد، وغیرہ)",
        "speak_now": "اپنی علامات بولیں...",
        "transcribing": "ٹرانسکرائب ہو رہا ہے...",
        "input_placeholder": "اپنی علامات بیان کریں یا طبی سوال پوچھیں...",
        "thinking": "AI ڈاکٹر سے مشورہ کر رہے ہیں...",
        "analyze_image_prompt": "براہ کرم اس طبی تصویر کا تجزیہ کریں۔",
        "history_title": "📋 تشخیص کی تاریخ",
        "no_history": "ابھی تک کوئی تاریخ نہیں۔ گفتگو شروع کریں!",
        "clear_history": "🗑️ تاریخ صاف کریں",
        "med_tracker_title": "💊 دوائی ٹریکر",
        "add_medicine": "دوائی شامل کریں",
        "med_name": "دوائی کا نام",
        "dosage": "خوراک",
        "timing": "وقت",
        "duration": "مدت",
        "notes": "نوٹس (اختیاری)",
        "save_med": "دوائی محفوظ کریں",
        "your_medicines": "آپ کی دوائیاں",
        "no_meds": "ابھی تک کوئی دوائی شامل نہیں۔",
        "morning": "🌅 صبح",
        "night": "🌙 رات",
        "after_meals": "🍽️ کھانے کے بعد",
        "before_meals": "کھانے سے پہلے",
        "twice_daily": "دن میں دو بار",
        "dashboard_title": "📊 مریض ڈیش بورڈ",
        "total_chats": "کل مشاورتیں",
        "active_meds": "فعال دوائیاں",
        "recent_diagnosis": "حالیہ تشخیصات",
        "medicine_history": "دوائی کی تاریخ",
        "query": "سوال",
        "response": "جواب",
        "date": "تاریخ",
        "status": "حالت",
        "active": "فعال",
        "stopped": "بند",
        "stop": "بند کریں",
        "delete": "حذف کریں",
    },
}

# Fallback to English for unsupported languages
def translate_ui(lang: str) -> dict:
    return _UI_STRINGS.get(lang, _UI_STRINGS["English"])
